# 03/12/2025

  - image   : olle_e_johansson.jpg
    day     : 3/12/2025
    time    : 09:00 - 13:00
    name    : Olle E. Johansson
    bio     : >-
              Olle E. Johansson is a consultant in the area of realtime communication 
              and in embedded system security. He has been active in Open Source for 
              many years as a developer, evangelist, trainer and speaker in many 
              conferences worldwide. Olle is a member of the OWASP SBOM Forum and the 
              OWASP CycloneDX industry working group. He is currently working on the 
              CycloneDX Transparency Exchange API standard. Olle is currently a project 
              leader for the Swedish DNS TAPIR project that is building Open Source 
              software for analysing DNS resolver logs and finding bad actors. 
    title   : 
    abstract: 
    feed    :
    url     : 
    linkedin: https://www.linkedin.com/in/ollejohansson/
    x_handle:
    reqs    : 
    urltag  : 
    display : yes
    confirmed: yes